# Generated by Django 5.1.3 on 2025-04-24 11:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Optional title/description for the image (e.g., 'Sports Day')", max_length=100)),
                ('image', models.ImageField(upload_to=core.models.carousel_image_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption overlay', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this image from the carousel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='academic_year',
            field=models.CharField(default='N/A', help_text='e.g., 2024-2025', max_length=20),
        ),
    ]
