# Generated by Django 5.1.3 on 2025-04-25 01:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsarticle_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, help_text="Optional: Student's profile picture.", null=True, upload_to=core.models.student_profile_picture_path),
        ),
    ]
